### ISSUE TITLE
Catching emitted value from a component using defineEmits

### ISSUE THREAD

**Issue by Smrtnyk** [vitest-community/vitest-browser-vue#1]
Is it possible to catch emitted value from a component after submit button on a form in the component is clicked?

**Comment by hezhengxu2018** [comment]
https://github.com/vitest-dev/vitest-browser-vue/blob/f5fd71b21537f1d7efe73c765b181db7e4b153ca/src/pure.ts#L66
maybe should return the wrapper here, and use the `findComponent` function of  `vue-test-utils` to get the componet you need.

**Comment by Smrtnyk** [comment]
Actually I am able to use screen.emitted, and it contains the entry for the emitted event and its values

for example a test like this works for me
```typescript
it(`emits "delete-item" event when delete button is clicked`, async () => {
        const deleteButton = page.getByAltText("Delete Chocolate Bar");
        expect(deleteButton.elements().length).toBe(1);

        await userEvent.click(deleteButton);

        const emittedEvents = screen.emitted("delete-item");
        expect(emittedEvents).toBeTruthy();
        expect(emittedEvents.length).toBe(1);
        expect(emittedEvents[0][0]).toStrictEqual(sampleItems[1]);
    });
```
