### ISSUE TITLE
Components mounted with defineComponent work only if vitest-browser-vue is imported

### ISSUE THREAD

**Issue by os-tohe** [vitest-community/vitest-browser-vue#2]
After installing Vitest browser related packages and this package, and setting up all the configurations, all of the tests which are made with `mount(defineComponent(...))` stopped working. I was able to make them work by either importing the `import 'vitest-browser-vue'` in the test file or in the file that I have added in my vite config setupFiles. For example this test does not work without importing the package:

```ts
import { mount } from '@vue/test-utils';
import { defineComponent } from 'vue';

const MyComponent = defineComponent({
  name: 'MyComponent',
  template: `
      <div class="my-div"></div>
    `,
});

test('Checkbox with mode "all" is checked if other checkbox is checked', async () => {
  const wrapper = mount(MyComponent);

  const div = wrapper.find('.my-div');
  console.log('div', div);
});
```

Without importing the package the console log throws this error:
```bash
PrettyFormatPluginError: Cannot call $$typeof on an empty DOMWrapper.
```

It seems that the vitest-browser-vue vite config does not seem to inject the package correctly.

**Versions:**
vitest-browser-vue 0.0.1
vitest 2.1.3
@vitest/browser 2.1.3
playwright 1.48.1
@vitest/coverage-v8 2.1.3

**vite.config.ts**
```ts
test: {
    setupFiles: ['vitest-browser-vue', './src/testSetup.ts'],
    globals: true,
    environment: 'happy-dom',
    css: true,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'json'],
      reportOnFailure: true,
    },
    reporters: ['junit', 'verbose'],
    outputFile: {
      junit: './junit-report.xml',
    },
    browser: {
      provider: 'playwright',
      enabled: true,
      name: 'chromium',
      providerOptions: {
        launch: {
          devtools: true,
        },
      },
    },
  },
```

**Comment by sheremet-va** [comment]
Why are you using `@vue/test-utils` instead of `vitest-browser-vue` if you intend to use this package? 🤔

**Comment by os-tohe** [comment]
So this is not compatible with `@vue/test-utils`? We don't want to rewrite all of our tests and I would also imagine the performance and speed is better when using `@vue/test-utils` since it only simulates dom?

**Comment by sheremet-va** [comment]
`@vue/test-utils` doesn't simulate DOM, it just renders components, `vitest-browser-vue` uses `@vue/test-utils` under the hood. DOM is simulated only when tests are running in Node.js, the whole point of running tests in the browser is to use actual DOM APIs.

Did you try using `@vue/test-utils` without this dependency? Does it work?

**Comment by os-tohe** [comment]
Alright good to know that!

Yes we have used `@vue/test-utils` for months and now that we installed the vitest browser related packages and configurations the tests made with `defineComponent` and `mount` stopped working. They now only work if we import the `vitest-browser-vue` package in the test file or in our test setup file.

Another reason why we still want to keep the `@vue/test-utils` and `mount` code is the fact that there does not seem to be any way to modify the props of the component when using the `render` function from your package? In `mount` you can change the props by calling `setProps` on the wrapper. And who knows what else this package is missing that is found in the `@vue/test-utils`.

**Comment by sheremet-va** [comment]
If you are not using [`vitest-browser-vue`](https://github.com/vitest-dev/vitest-browser-vue) to render components, then you don't need to install it and can continue to use `@vue/test-utils`.

> In `mount` you can change the props by calling `setProps` on the wrapper.

You can use `rerender` to do the same thing with `vitest-browser-vue`:

```ts
const screen = render(Component, { props: { name:  'Old' } })
screen.rerender({ name: 'New' })
```

> And who knows what else this package is missing that is found in the `@vue/test-utils`.

Most methods from `mount` are not exposed to encourage behaviour tests instead of testing the implementation detail. From https://testing-library.com/docs/vue-testing-library/intro/#the-problem:

> ...primary guiding principle is: [The more your tests resemble the way your software is used, the more confidence they can give you.](https://testing-library.com/docs/guiding-principles)

**Comment by os-tohe** [comment]
Thanks for the info! I am using `vitest-browser-vue` in some test files but not on all. I just realized that using different [workspaces](https://vitest.dev/guide/workspace) for the files which use the `@vue/test-utils` and for the files which use `vitest-browser-vue` might solve this issue. Now I just need to figure out how to properly setup the workspaces.

EDIT: By using the workspaces I was able to leave all of my old tests intact while also supporting `vitest-browser-vue` in some files. Now whenever I want to add a test file which uses this package, I just need to name it `.browser.test.ts`.

Here is my `vitest.workspace.ts` file if anyone is interested:
```ts
// vitest.workspace.ts
import { defineWorkspace } from 'vitest/config';

const browserTests = '**/*.browser.{test,spec}.ts';

export default defineWorkspace([
  {
    extends: './vite.config.js',
    test: {
      include: ['**/*.{test,spec}.ts'],
      exclude: [browserTests],
      globals: true,
      environment: 'happy-dom',
      css: true,
    },
  },
  {
    extends: './vite.config.js',
    test: {
      include: [browserTests],
      setupFiles: ['./src/testSetup.ts', 'vitest-browser-vue'],
      globals: true,
      css: true,
      browser: {
        provider: 'playwright',
        enabled: true,
        name: 'chromium',
        providerOptions: {
          launch: {
            devtools: true,
          },
        },
      },
    },
  },
]);
```
