### ISSUE TITLE
[feature request] export `vm`  for users to get access to the component instance

### ISSUE THREAD

**Issue by LoTwT** [vitest-community/vitest-browser-vue#3]
## description

It can't bind the template refs when mounting components by `render` from `vitest-browser-vue` or `mount` from `@vue/test-utils`.  In some cases, it's necessary to test `properties` explicitly exposed by the component.

The `VueWrapper` of `@vue/test-utils` provides the property `vm` for uses to get access to the [component instance](https://test-utils.vuejs.org/guide/advanced/component-instance.html).

I think it's necessary and better to export `vm` in the `RenderResult`.

**Comment by sheremet-va** [comment]
This library follows the same principle that [`testing-library` established](https://testing-library.com/docs/guiding-principles):

> The more your tests resemble the way your software is used, the more confidence they can give you.

Users do not have access to the component instance, they see the element in the browser. `vm` represents an implementation detail, and we discourage its usage.

**Comment by LoTwT** [comment]
Hi @sheremet-va 

Could you take a look at [this issue](https://github.com/vuejs/test-utils/issues/2542)? And the reproduction link is https://stackblitz.com/edit/vitest-dev-vitest-fyfyzq?file=test%2Fsfc.test.ts.

If someone wants to test the functions or properties exposed using `defineExpose` by a custom component, I think getting access to the component instance is necessary.
