### ISSUE TITLE
How to Simulate Drag Behavior?

### ISSUE THREAD

**Issue by String10** [vitest-community/vitest-browser-vue#5]
playwright gives guide like this:
``` typescript
await page.locator('#item-to-be-dragged').hover();
await page.mouse.down();
await page.locator('#item-to-drop-at').hover();
await page.mouse.up();
```
but in vitest browser mode there's not a thing like the `mouse` mentioned above,
and the locators created by `page.elementLocator` don't support mousedown event, either.

i also tried to use `dispatchEvent` but it never works. 😢

i'm expecting a mousedown-mousemove-mouseup event sequence with ctrl key held,
more specifically, i'm testing a box selection function on svg elements,
which needs to hold ctrl key then drag to select a box range.
could anyone give a workaround or just give it a try to support more complicated mouse event? thx!

**Comment by Smrtnyk** [comment]
https://vitest.dev/guide/browser/interactivity-api#userevent-draganddrop

**Comment by String10** [comment]
> https://vitest.dev/guide/browser/interactivity-api#userevent-draganddrop

@Smrtnyk thanks for your response!

but i forgot to mention that i needs a drag event with ctrl key holding,
seems like the drag-and-drop event doesn't have a option to set that?

**Comment by sheremet-va** [comment]
> > [vitest.dev/guide/browser/interactivity-api#userevent-draganddrop](https://vitest.dev/guide/browser/interactivity-api#userevent-draganddrop)
> 
> @Smrtnyk thanks for your response!
> 
> but i forgot to mention that i needs a drag event with ctrl key holding, seems like the drag-and-drop event doesn't have a option to set that?

Can you press it with `userEvent.keyboard('{Control}')`?

```ts
await userEvent.keyboard('{Control}')
await userEvent.dragAndDrop(element1, element2)
```

**Comment by String10** [comment]
@sheremet-va omg it works! thanks a lot!

i finally achieved that by this
``` typescript
await userEvent.keyboard('{Control>}') // use '>' to press it without releasing
await userEvent.dragAndDrop(element1, element2)
```

from this [doc](https://testing-library.com/docs/user-event/keyboard/)
> Keys can be kept pressed by adding a > to the end of the descriptor.
